version: '3.8'

services:
  # Main development environment for Phase 3 stores
  nostr-unchained-dev:
    build:
      context: .
      dockerfile: Dockerfile.phase3.dev
    container_name: nostr-unchained-phase3-dev
    ports:
      - "3000:3000"      # Main dev server
      - "5173:5173"      # Vite dev server
      - "8080:8080"      # Test server 1
      - "8081:8081"      # Test server 2
    volumes:
      - .:/app
      - /app/node_modules
      - ./test-results:/app/test-results
      - ./coverage:/app/coverage
    environment:
      - NODE_ENV=development
      - PHASE=3
      - SVELTE_DEV=true
      - VITE_TEST_MODE=true
      - UMBREL_RELAY=ws://umbrel.local:4848
      - STORE_TEST_MODE=true
    networks:
      - nostr-network
    extra_hosts:
      - "umbrel.local:host-gateway"
    depends_on:
      - test-runner

  # Dedicated test runner for continuous testing  
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.phase3.dev
    container_name: nostr-unchained-phase3-tests
    volumes:
      - .:/app
      - /app/node_modules
      - ./test-results:/app/test-results
      - ./coverage:/app/coverage
    environment:
      - NODE_ENV=test
      - PHASE=3
      - CI=true
      - UMBREL_RELAY=ws://umbrel.local:4848
      - STORE_TEST_RELAY=ws://umbrel.local:4848
    extra_hosts:
      - "umbrel.local:host-gateway"
    command: npm run test:phase3:watch
    networks:
      - nostr-network

  # Multi-tab testing environment with Umbrel relay
  multi-tab-tester:
    build:
      context: .
      dockerfile: Dockerfile.phase3.dev
    container_name: nostr-unchained-phase3-multitab
    ports:
      - "9080:8080"
      - "9081:8081"
    volumes:
      - .:/app
      - /app/node_modules
      - ./test-results:/app/test-results
    environment:
      - NODE_ENV=test
      - PHASE=3
      - MULTI_TAB_TEST=true
      - PLAYWRIGHT_BROWSERS_PATH=/opt/playwright
      - UMBREL_RELAY=ws://umbrel.local:4848
      - CROSS_TAB_RELAY=ws://umbrel.local:4848
    extra_hosts:
      - "umbrel.local:host-gateway"
    command: npm run test:cross-tab:watch
    networks:
      - nostr-network

  # SSR testing environment
  ssr-tester:
    build:
      context: .
      dockerfile: Dockerfile.phase3.dev
    container_name: nostr-unchained-phase3-ssr
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./test-results:/app/test-results
    environment:
      - NODE_ENV=production
      - PHASE=3
      - SSR_TEST=true
      - SVELTEKIT_MODE=true
      - UMBREL_RELAY=ws://umbrel.local:4848
    extra_hosts:
      - "umbrel.local:host-gateway"
    command: npm run test:ssr:watch
    networks:
      - nostr-network

  # Umbrel relay health monitor
  relay-monitor:
    build:
      context: .
      dockerfile: Dockerfile.phase3.dev
    container_name: nostr-unchained-relay-monitor
    volumes:
      - ./test-results:/app/test-results
    environment:
      - NODE_ENV=test
      - UMBREL_RELAY=ws://umbrel.local:4848
      - MONITOR_MODE=true
    extra_hosts:
      - "umbrel.local:host-gateway"
    command: npm run monitor:relay:umbrel
    networks:
      - nostr-network

networks:
  nostr-network:
    driver: bridge 