version: '3.8'

services:
  # Main development environment
  crypto-dev:
    build:
      context: .
      dockerfile: Dockerfile.crypto-dev
    ports:
      - "3000:3000"    # Main dev server
      - "9229:9229"    # Node.js debugging
    volumes:
      - .:/app
      - /app/node_modules
      - crypto-cache:/app/.crypto-cache
    environment:
      - NODE_ENV=development
      - CRYPTO_DEV_MODE=true
      - DEBUG=crypto:*
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    command: npm run dev:crypto
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Isolated crypto testing
  crypto-testing:
    build:
      context: .
      dockerfile: Dockerfile.crypto-dev
    volumes:
      - .:/app
      - /app/node_modules
      - test-results:/app/test-results
    environment:
      - NODE_ENV=test
      - NIP44_COMPLIANCE_MODE=strict
      - CRYPTO_TEST_VERBOSE=true
    command: npm run test:crypto:watch
    depends_on:
      crypto-dev:
        condition: service_healthy

  # Security audit service
  security-audit:
    build:
      context: .
      dockerfile: Dockerfile.crypto-dev
    volumes:
      - .:/app
      - audit-reports:/app/audit-reports
    environment:
      - AUDIT_MODE=cryptographic
      - SECURITY_LEVEL=maximum
    command: npm run audit:crypto:full
    profiles: ["security"]

  # Performance benchmarking
  crypto-benchmark:
    build:
      context: .
      dockerfile: Dockerfile.crypto-dev
    volumes:
      - .:/app
      - /app/node_modules
      - benchmark-results:/app/benchmarks/results
    environment:
      - NODE_ENV=benchmark
      - BENCHMARK_ITERATIONS=10000
    command: npm run benchmark:crypto
    profiles: ["performance"]

  # NIP-44 compliance validation
  nip44-compliance:
    build:
      context: .
      dockerfile: Dockerfile.crypto-dev
    volumes:
      - .:/app
      - /app/node_modules
      - compliance-reports:/app/compliance
    environment:
      - COMPLIANCE_MODE=nip44-strict
      - TEST_VECTORS_URL=https://github.com/nostr-protocol/nips/raw/master/44-test-vectors.json
    command: npm run test:nip44:compliance
    profiles: ["compliance"]

volumes:
  crypto-cache:
    driver: local
  test-results:
    driver: local
  audit-reports:
    driver: local
  benchmark-results:
    driver: local
  compliance-reports:
    driver: local

networks:
  crypto-network:
    driver: bridge 