version: '3.8'

services:
  # Ephemeral Nostr Relay für Tests - Keine Persistenz
  nostr-relay:
    image: scsibug/nostr-rs-relay:latest
    ports:
      - "7777:8080"
    environment:
      # In-Memory Database - keine Persistenz
      - "RELAY_DB_URL=sqlite://:memory:"
      - "RUST_LOG=warn,nostr_rs_relay=info"
      # Relay-spezifische Config
      - "RELAY_NAME=Test Relay"
      - "RELAY_DESCRIPTION=Ephemeral relay for nostr-unchained tests"
      - "RELAY_PUBKEY=test"
      # Keine Rate Limits für Tests
      - "RELAY_MAX_MESSAGE_LENGTH=131072"
      - "RELAY_MAX_SUBSCRIPTIONS=100"
      - "RELAY_MAX_FILTERS=100"
    tmpfs:
      # Alles im RAM
      - /tmp
      - /var/log
    mem_limit: 256m
    restart: "no"  # Kein Restart für Tests
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Secondary Relay für Multi-Relay Tests
  relay-2:
    image: scsibug/nostr-rs-relay:latest
    ports:
      - "7778:8080"
    environment:
      - "RELAY_DB_URL=sqlite://:memory:"
      - "RUST_LOG=warn,nostr_rs_relay=info"
      - "RELAY_NAME=Test Relay 2"
      - "RELAY_DESCRIPTION=Secondary relay for multi-relay tests"
      - "RELAY_PUBKEY=test2"
      - "RELAY_MAX_MESSAGE_LENGTH=131072"
      - "RELAY_MAX_SUBSCRIPTIONS=100"
      - "RELAY_MAX_FILTERS=100"
    tmpfs:
      - /tmp
      - /var/log
    mem_limit: 256m
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Tertiary Relay für erweiterte Multi-Relay Tests
  relay-3:
    image: scsibug/nostr-rs-relay:latest
    ports:
      - "7779:8080"
    environment:
      - "RELAY_DB_URL=sqlite://:memory:"
      - "RUST_LOG=warn,nostr_rs_relay=info"
      - "RELAY_NAME=Test Relay 3"
      - "RELAY_DESCRIPTION=Tertiary relay for advanced multi-relay tests"
      - "RELAY_PUBKEY=test3"
      - "RELAY_MAX_MESSAGE_LENGTH=131072"
      - "RELAY_MAX_SUBSCRIPTIONS=100"
      - "RELAY_MAX_FILTERS=100"
    tmpfs:
      - /tmp
      - /var/log
    mem_limit: 256m
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  default:
    name: nostr-test-network